# Topic 2.5 - Pandas 的排序与聚合运算

本节开始前，我们先导入 Pandas 库：

In [236]:
import pandas as pd

## 1. 数据排序

### (1) 基本排序方法

在 Pandas 中，可以使用 `sort_values()` 方法对 DataFrame 进行排序，当中可以强调以下参数：

- `by`：指定排序的列名，可以是单个列名或多个列名组成的列表
- `ascending`：指定排序的顺序，默认为 `True`（升序），如果设置为 `False` 则为降序，应该与 `by` 参数中的排序依据的列一一对应
- `inplace`：指定是否在原 DataFrame 上进行排序，默认为 `False` 就是返回一个新的 DataFrame，设置为 `True` 则会修改原 DataFrame 而不返回新的 DataFrame

我们先来看一个简单的例子，就是之前的学生成绩数据表：

In [237]:
df1 = pd.read_csv("../data/students.csv")
df1

             name  class  gender  age  chinese  math  english
0   Alice Johnson      1  Female   18       85    88       90
1       Bob Smith      2    Male   19       78    75       80
2   Charlie Brown      3    Male   18       92    90       94
3    David Miller      1    Male   20       88    85       87
4     Emma Wilson      2  Female   19       76    78       74
..            ...    ...     ...  ...      ...   ...      ...
86   Jonah Larson      3    Male   21       78    76       77
87   Kylie Newman      1  Female   18       85    83       84
88   Lucas Porter      2    Male   22       91    92       93
89   Megan Arnold      3  Female   19       79    77       78
90    Nick Keller      1    Male   20       87    85       88

[91 rows x 7 columns]

- 在这个表中，我们想将所有数据按照 "数学成绩" 这一列进行降序排序，可以使用以下代码实现：

In [238]:
df1.sort_values(by="math", ascending=False, inplace=True)
df1

               name  class  gender  age  chinese  math  english
71   Ursula Griffin      3  Female   21       93    95       94
27     Brian Turner      1    Male   18       93    95       94
48       Wendy Wood      1  Female   22       93    95       94
40   Ophelia Morgan      2  Female   20       92    94       93
82      Felix Stone      2    Male   18       92    94       93
..              ...    ...     ...  ...      ...   ...      ...
28   Cathy Phillips      2  Female   22       76    74       75
56  Ethan Henderson      3    Male   21       75    73       74
34     Isla Stewart      2  Female   19       74    72       73
22      Will Nelson      2    Male   18       75    72       74
10        Karen Lee      2  Female   20       73    70       75

[91 rows x 7 columns]

- 如果我们想按照多个列进行排序，比如先按 "语文成绩" 降序排序，再按 "数学成绩" 升序排序，这里的逻辑是，先按照语文成绩降序排序，如果语文成绩相同，再按照数学成绩升序排序，对应的代码是：

In [239]:
df1.sort_values(by=["chinese", "math"], ascending=[False, True], inplace=True)
df1

               name  class  gender  age  chinese  math  english
11       Leo Walker      3    Male   21       95    94       96
71   Ursula Griffin      3  Female   21       93    95       94
27     Brian Turner      1    Male   18       93    95       94
48       Wendy Wood      1  Female   22       93    95       94
2     Charlie Brown      3    Male   18       92    90       94
..              ...    ...     ...  ...      ...   ...      ...
4       Emma Wilson      2  Female   19       76    78       74
22      Will Nelson      2    Male   18       75    72       74
56  Ethan Henderson      3    Male   21       75    73       74
34     Isla Stewart      2  Female   19       74    72       73
10        Karen Lee      2  Female   20       73    70       75

[91 rows x 7 columns]

### (2) 排序后重排行号

在上面的例子中，大家应该注意到，排序后 DataFrame 的行号是乱的，因为排序只是改变了数据的顺序，但并没有改变行号

- 如果我们想在排序后重新设置行号，可以使用 `reset_index()` 方法
- 这里我们通常会设置 `drop=True` 参数来丢弃原有的行号列，否则原来的行号会成为一个新的列被保留下来

In [240]:
df1.sort_values(by="english", ascending=True, inplace=True)
df1.reset_index(drop=True, inplace=True)
df1

               name  class  gender  age  chinese  math  english
0      Isla Stewart      2  Female   19       74    72       73
1   Ethan Henderson      3    Male   21       75    73       74
2       Will Nelson      2    Male   18       75    72       74
3       Emma Wilson      2  Female   19       76    78       74
4         Karen Lee      2  Female   20       73    70       75
..              ...    ...     ...  ...      ...   ...      ...
86    Charlie Brown      3    Male   18       92    90       94
87       Wendy Wood      1  Female   22       93    95       94
88     Brian Turner      1    Male   18       93    95       94
89   Ursula Griffin      3  Female   21       93    95       94
90       Leo Walker      3    Male   21       95    94       96

[91 rows x 7 columns]

### (3) Pandas 中的 `inplace` 参数

在大多数 Pandas 方法中，都会有一个 `inplace` 参数，这个参数的作用是决定操作是直接在原 DataFrame 上进行修改，还是返回一个新的 DataFrame

- 如果 `inplace=True`，那么操作会直接修改原 DataFrame，不会返回新的 DataFrame
- 如果 `inplace=False`（默认值），那么操作会返回一个新的 DataFrame

这个操作，大家其实之前是体会过的，我们介绍列表操作时，就提到过类似的概念：

- 比如 `list.sort()` 方法就是直接在原列表上进行排序
- 而 `sorted(list)` 函数则是返回一个新的排序后的列表

我们来体会一下 `inplace` 参数的作用：

- 首先我们在排序中设置一个 `inplace=True`，这个操作会直接在原 DataFrame 上进行修改：

In [241]:
df2 = pd.read_csv("../data/students.csv")
df2

             name  class  gender  age  chinese  math  english
0   Alice Johnson      1  Female   18       85    88       90
1       Bob Smith      2    Male   19       78    75       80
2   Charlie Brown      3    Male   18       92    90       94
3    David Miller      1    Male   20       88    85       87
4     Emma Wilson      2  Female   19       76    78       74
..            ...    ...     ...  ...      ...   ...      ...
86   Jonah Larson      3    Male   21       78    76       77
87   Kylie Newman      1  Female   18       85    83       84
88   Lucas Porter      2    Male   22       91    92       93
89   Megan Arnold      3  Female   19       79    77       78
90    Nick Keller      1    Male   20       87    85       88

[91 rows x 7 columns]

In [242]:
df2.sort_values(by="math", ascending=False, inplace=True)
df2

               name  class  gender  age  chinese  math  english
71   Ursula Griffin      3  Female   21       93    95       94
27     Brian Turner      1    Male   18       93    95       94
48       Wendy Wood      1  Female   22       93    95       94
40   Ophelia Morgan      2  Female   20       92    94       93
82      Felix Stone      2    Male   18       92    94       93
..              ...    ...     ...  ...      ...   ...      ...
28   Cathy Phillips      2  Female   22       76    74       75
56  Ethan Henderson      3    Male   21       75    73       74
34     Isla Stewart      2  Female   19       74    72       73
22      Will Nelson      2    Male   18       75    72       74
10        Karen Lee      2  Female   20       73    70       75

[91 rows x 7 columns]

- 接下来，我们再来看看如果设置 `inplace=False`，这个操作会将排序结果返回为一个新的 DataFrame，而不会修改原 DataFrame：

In [243]:
df3 = pd.read_csv("../data/students.csv")
df3

             name  class  gender  age  chinese  math  english
0   Alice Johnson      1  Female   18       85    88       90
1       Bob Smith      2    Male   19       78    75       80
2   Charlie Brown      3    Male   18       92    90       94
3    David Miller      1    Male   20       88    85       87
4     Emma Wilson      2  Female   19       76    78       74
..            ...    ...     ...  ...      ...   ...      ...
86   Jonah Larson      3    Male   21       78    76       77
87   Kylie Newman      1  Female   18       85    83       84
88   Lucas Porter      2    Male   22       91    92       93
89   Megan Arnold      3  Female   19       79    77       78
90    Nick Keller      1    Male   20       87    85       88

[91 rows x 7 columns]

In [244]:
df3_new = df3.sort_values(by="chinese", ascending=False, inplace=False)

display(df3_new)
display(df3)

               name  class  gender  age  chinese  math  english
11       Leo Walker      3    Male   21       95    94       96
71   Ursula Griffin      3  Female   21       93    95       94
27     Brian Turner      1    Male   18       93    95       94
48       Wendy Wood      1  Female   22       93    95       94
21       Vera Baker      1  Female   21       92    94       93
..              ...    ...     ...  ...      ...   ...      ...
4       Emma Wilson      2  Female   19       76    78       74
22      Will Nelson      2    Male   18       75    72       74
56  Ethan Henderson      3    Male   21       75    73       74
34     Isla Stewart      2  Female   19       74    72       73
10        Karen Lee      2  Female   20       73    70       75

[91 rows x 7 columns]

             name  class  gender  age  chinese  math  english
0   Alice Johnson      1  Female   18       85    88       90
1       Bob Smith      2    Male   19       78    75       80
2   Charlie Brown      3    Male   18       92    90       94
3    David Miller      1    Male   20       88    85       87
4     Emma Wilson      2  Female   19       76    78       74
..            ...    ...     ...  ...      ...   ...      ...
86   Jonah Larson      3    Male   21       78    76       77
87   Kylie Newman      1  Female   18       85    83       84
88   Lucas Porter      2    Male   22       91    92       93
89   Megan Arnold      3  Female   19       79    77       78
90    Nick Keller      1    Male   20       87    85       88

[91 rows x 7 columns]

## 2. 数据聚合运算

### (1) 数据的截面聚合

#### (a) 截面聚合方法

上一节我们讲过一些基本的统计计算，比如 `mean()`、`sum()`、`max()`、`min()` 等方法，这些方法都是对整个列进行计算的

- 而有时，我们并不想对整列进行计算，而是想根据某些条件对数据进行分组，然后对每个组进行聚合计算
- 例如在我们的学生成绩表中，我们想计算每个班级的数学成绩平均分，一班、二班、三班分别来算

这时我们就要用到 Pandas 的 `groupby()` 方法：

- 这个方法接收一个或多个列名作为分组依据，然后返回一个 `GroupBy` 对象
- 之后，我们可以对这个对象调用聚合方法，比如 `mean()` 来计算每个组的平均值

我们在学生成绩表上来应用一下 `groupby()` 方法：

- 首先，我们按照班级求数学成绩的平均分，或者三科的平均分：

In [245]:
df4 = pd.read_csv("../data/students.csv")
df4

             name  class  gender  age  chinese  math  english
0   Alice Johnson      1  Female   18       85    88       90
1       Bob Smith      2    Male   19       78    75       80
2   Charlie Brown      3    Male   18       92    90       94
3    David Miller      1    Male   20       88    85       87
4     Emma Wilson      2  Female   19       76    78       74
..            ...    ...     ...  ...      ...   ...      ...
86   Jonah Larson      3    Male   21       78    76       77
87   Kylie Newman      1  Female   18       85    83       84
88   Lucas Porter      2    Male   22       91    92       93
89   Megan Arnold      3  Female   19       79    77       78
90    Nick Keller      1    Male   20       87    85       88

[91 rows x 7 columns]

In [246]:
df4.groupby("class")["math"].mean()

class
1    84.645161
2    83.166667
3    83.633333
Name: math, dtype: float64

In [247]:
df4.groupby("class")[["math", "chinese", "english"]].mean()

            math    chinese    english
class
1      84.645161  85.612903  86.000000
2      83.166667  83.766667  83.966667
3      83.633333  84.500000  84.700000

- 接着，我们还可以既按照班级分组，又按照性别分组，来计算每个班级中男生和女生的数学成绩平均分，或者三科的平均分：

In [248]:
df4.groupby(["class", "gender"])["math"].mean()

class  gender
1      Female    86.062500
       Male      83.133333
2      Female    83.714286
       Male      82.687500
3      Female    83.857143
       Male      83.437500
Name: math, dtype: float64

In [249]:
df4.groupby(["class", "gender"])[["math", "chinese", "english"]].mean()

                   math    chinese    english
class gender
1     Female  86.062500  86.375000  87.187500
      Male    83.133333  84.800000  84.733333
2     Female  83.714286  83.857143  84.000000
      Male    82.687500  83.687500  83.937500
3     Female  83.857143  84.357143  84.714286
      Male    83.437500  84.625000  84.687500

要注意，本身 `groupby()` 方法并不会改变原 DataFrame，而是返回一个 `GroupBy` 对象：

- 也就是说，只告诉 Pandas 我们要把数据进行聚合，又不说聚在一起做什么，是不会有任何计算发生的
- 只有在之后调用聚合方法时，才会进行实际的计算并返回结果

In [250]:
df4.groupby("class")

#### (b) 截面聚合后的数据处理

大家可以看到，将数据按类别分组聚合后，返回的结果是一个新的 DataFrame：

- 这个 DataFrame 的格式其实是我们之前提到的 MultiIndex 格式，也就是数据透视表
- 那么要想将这个数据透视表还原成普通的 DataFrame 格式，可以使用 `reset_index()` 方法

In [251]:
df4.groupby(["class", "gender"])[["math", "chinese", "english"]].mean().reset_index()

   class  gender       math    chinese    english
0      1  Female  86.062500  86.375000  87.187500
1      1    Male  83.133333  84.800000  84.733333
2      2  Female  83.714286  83.857143  84.000000
3      2    Male  82.687500  83.687500  83.937500
4      3  Female  83.857143  84.357143  84.714286
5      3    Male  83.437500  84.625000  84.687500

#### (c) Pandas 中的方法链

在上面的操作中，我们使用了一连串的方法调用：`df4.groupby(...)[...].mean().reset_index()` 

- 这种形式被称为方法链（method chaining），它允许我们将多个方法调用串联在一起，使代码更加简洁和易读
- 当然，有个更好的习惯是，每个方法调用后面都换行，并且使用括号将整个方法链首尾包裹起来（不加括号换行会报错），这样代码会更清晰一些：

In [252]:
df4_mean_scores = (
    df4.groupby(["class", "gender"])[["math", "chinese", "english"]]
    .mean()
    .reset_index()
)
df4_mean_scores

   class  gender       math    chinese    english
0      1  Female  86.062500  86.375000  87.187500
1      1    Male  83.133333  84.800000  84.733333
2      2  Female  83.714286  83.857143  84.000000
3      2    Male  82.687500  83.687500  83.937500
4      3  Female  83.857143  84.357143  84.714286
5      3    Male  83.437500  84.625000  84.687500

### (2) 数据的时间聚合

#### (a) 时间聚合方法

除了按类别分组进行聚合计算外，Pandas 还支持按时间窗口进行聚合计算，使用的是 `resample()` 方法：

- `resample()` 方法适用于时间序列数据，可以按照指定的时间频率对数据进行重采样，然后对每个时间窗口进行聚合计算：

    - `resample(rule="YS")` 表示按年重采样
    - `resample(rule="ME")` 表示按月重采样
    - `resample(rule="W")` 表示按周重采样
    - `resample(rule="D")` 表示按天重采样
    - `resample(rule="H")` 表示按小时重采样
    - `resample(rule="T")` 表示按分钟重采样
    - `resample(rule="S")` 表示按秒重采样

- 当然，`resample()` 方法要求数据本身有一个时间索引（DatetimeIndex），否则无法进行时间重采样
- 这里我们先导入之前见过的销售数据，并且将索引改为 `date` 列，再改为时间格式，再算出一个 `revenue` 列为 `price` 和 `quantity` 的乘积：

In [253]:
df5 = pd.read_excel("../data/sales.xlsx", sheet_name="sales")
df5['date'] = pd.to_datetime(df5['date'])
df5.set_index('date', inplace=True)

df5['revenue'] = df5['price'] * df5['quantity']
df5

             product  price  quantity  revenue
date
2024-01-01    Camera   4599         6    27594
2024-01-01   Monitor   1599         5     7995
2024-01-01    Tablet   2999        11    32989
2024-01-01     Phone   4999         4    19996
2024-01-01    Laptop   6999        10    69990
...              ...    ...       ...      ...
2024-02-29   Speaker    899        11     9889
2024-02-29  Keyboard    399        11     4389
2024-02-29    Laptop   6999        10    69990
2024-02-29  Keyboard    399        14     5586
2024-02-29    Laptop   6999        14    97986

[333 rows x 4 columns]

之后，我们就可以按时间来计算总销售额了：

- 首先，我们来看按月计算总销售额的例子：

In [254]:
df5.resample(rule="ME")["revenue"].sum()

date
2024-01-31    4054530
2024-02-29    4391709
Freq: ME, Name: revenue, dtype: int64

- 接着，我们来看一个按周计算总销售额的例子：

In [255]:
df5.resample(rule="W")["revenue"].sum()

date
2024-01-07    1004069
2024-01-14    1006881
2024-01-21     764904
2024-01-28     946609
2024-02-04     836333
2024-02-11    1248149
2024-02-18    1085734
2024-02-25     866033
2024-03-03     687527
Freq: W-SUN, Name: revenue, dtype: int64

- 当然，对多列也可以进行时间聚合计算，比如同时计算总销售额和总销量：

In [256]:
df5.resample(rule="ME")[["quantity", "revenue"]].sum()

            quantity  revenue
date
2024-01-31      1770  4054530
2024-02-29      1591  4391709

#### (b) 时间聚合后的数据处理

在使用 `resample()` 方法进行时间聚合后，返回的结果同样是一个新的 DataFrame：

- 这个新的 DataFrame 也是含有多重索引的，也就是说，是数据透视表格式的
- 如果想将其还原为普通的 DataFrame 格式，同样可以使用 `reset_index()` 方法
- 并且可以使用方法链的形式将这些操作串联起来：

In [257]:
df5_monthly_total = (df5.resample(rule="ME")[["quantity", "revenue"]]
                     .sum()
                     .reset_index()
                     )

df5_monthly_total

        date  quantity  revenue
0 2024-01-31      1770  4054530
1 2024-02-29      1591  4391709

## 3. 数据的窗口运算

### (1) 窗口运算的概念

窗口运算属于一种比较复杂的数据运算了，它常用于时间序列的运算中，我们先来说说它的概念：

- 窗口运算首先会定义一个固定大小的“窗口”，这个窗口会框出数据中的一部分，这部分数据可以进行求和、求平均等操作
- 然后，这个窗口会沿着数据移动，通常是从上到下移动，每次移动一个单位，重新框出一部分数据，再进行相同的计算
- 这样就可以得到一个新的序列，这个序列中的每个值都是对应窗口内数据的计算结果

这么说有些抽象，我们来看一个求移动平均的例子：

- 假设我们有一个时间序列数据，我们想计算 `Close` 这列的 3 天移动平均值：

<div align="center">
    <img src="./截屏2026-01-30 23.29.55.png" width="500"/>
</div>

- 这里我们定义了一个大小为 3 的窗口：

    - 首先框出前 3 天的数据，计算它们的平均值，得到第一个移动平均值
    - 接着，窗口向下移动一天，框出第 2 天到第 4 天的数据，计算它们的平均值，得到第二个移动平均值
    - 依此类推，直到整个数据序列都被处理完毕
    - 由于前两天的数据无法形成完整的 3 天窗口，因此对应的移动平均值为 NaN

### (2) Pandas 中的窗口运算方法

在 Pandas 中，可以使用 `rolling()` 方法来实现窗口运算：

- 当中我们要强调 `window` 参数用来指定窗口的大小，正数是从上到下，
- 并且与 `resample()` 和 `groupby()` 方法类似，`rolling()` 方法后面也需要接一个聚合方法，比如 `mean()` 来计算窗口内数据的平均值，不然的话，`rolling()` 方法本身并不会进行任何计算，只会返回一个滚动窗口对象

In [258]:
df6 = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=7, freq='D'),
    'Security': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'Close': [104, 120, 107, 103, 117, 109, 105]
})

df6

        Date Security  Close
0 2023-01-01        A    104
1 2023-01-02        A    120
2 2023-01-03        A    107
3 2023-01-04        A    103
4 2023-01-05        A    117
5 2023-01-06        A    109
6 2023-01-07        A    105

In [259]:
df6["Close_Avg_3"] = df6["Close"].rolling(window=3).mean()
df6

        Date Security  Close  Close_Avg_3
0 2023-01-01        A    104          NaN
1 2023-01-02        A    120          NaN
2 2023-01-03        A    107   110.333333
3 2023-01-04        A    103   110.000000
4 2023-01-05        A    117   109.000000
5 2023-01-06        A    109   109.666667
6 2023-01-07        A    105   110.333333

我们发现，使用 `rolling()` 时，其实并不需要将数据设置为时间索引：

- 只需要保证数据是按时间顺序排列的即可
- 因此，为了保险起见，我们通常会先将数据按时间排序，再进行窗口运算：

In [260]:
df6 = df6.sort_values(by="Date", ascending=True)
df6["Close_Avg_3"] = df6["Close"].rolling(window=3).mean()
df6

        Date Security  Close  Close_Avg_3
0 2023-01-01        A    104          NaN
1 2023-01-02        A    120          NaN
2 2023-01-03        A    107   110.333333
3 2023-01-04        A    103   110.000000
4 2023-01-05        A    117   109.000000
5 2023-01-06        A    109   109.666667
6 2023-01-07        A    105   110.333333

### (3) Pandas 中实现从下往上的窗口运算

Pandas 中的 `rolling()` 方法默认是从上往下进行窗口运算的，也就是正向滚动窗口。

如果我们想实现从下往上的窗口运算，也就是反向滚动窗口，可以通过以下方法：

- 先将数据翻转过来，使用 `iloc[::-1]` 方法
- 然后对翻转后的数据使用 `rolling()` 方法进行窗口运算
- 最后再将结果翻转回来，恢复原来的顺序，还是使用 `iloc[::-1]` 方法
- 这时候，尾部的数据由于无法形成完整的窗口，结果会是 NaN

例如，我们想计算 `Close` 列的 3 天反向移动平均值，可以使用以下代码实现：

In [261]:
df7 = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=7, freq='D'),
    'Security': ['A', 'A', 'A', 'A', 'A', 'A', 'A'],
    'Close': [104, 120, 107, 103, 117, 109, 105]
})

df7

        Date Security  Close
0 2023-01-01        A    104
1 2023-01-02        A    120
2 2023-01-03        A    107
3 2023-01-04        A    103
4 2023-01-05        A    117
5 2023-01-06        A    109
6 2023-01-07        A    105

In [263]:
df7["Close_Avg_3_reverse"] = df7["Close"].iloc[::-1].rolling(window=3).mean().iloc[::-1]
df7

        Date Security  Close  Close_Avg_3_reverse
0 2023-01-01        A    104           110.333333
1 2023-01-02        A    120           110.000000
2 2023-01-03        A    107           109.000000
3 2023-01-04        A    103           109.666667
4 2023-01-05        A    117           110.333333
5 2023-01-06        A    109                  NaN
6 2023-01-07        A    105                  NaN