# Topic 2.3 - Pandas 中的数据索引

Pandas 中的索引，是指将 DataFrame 中的数据进行标识和定位的方式，说白了就是将一部分数据提取出来，这种提取可以是：

- 提取出某列或某些列的数据
- 提取出某行或某些行的数据
- 既提取出某行又提取出某列的数据

我们就分别来讲解这几种提取数据的方式，我们先导入 pandas 库：

In [97]:
import pandas as pd

## 1. 按列索引

在 Pandas 中，按列索引是指通过列名来提取 DataFrame 中的一列或多列数据。常用的方法有以下几种：

### (1) 提取单列数据为 Series

我们之前提到过，如果想要提取 DataFrame 中的一列数据，提取出来以后其实是 Series，可以使用以下两种方式：

- 一种是使用方括号 `df['列名']`，这里必须使用引号将列名括起来：

In [98]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Melbourne', 'Sydney', 'Brisbane']
})

df1

      Name  Age       City
0    Alice   25  Melbourne
1      Bob   30     Sydney
2  Charlie   35   Brisbane

In [99]:
df1['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

- 还有一种是使用点号 `df.列名`：

    - 这种方式只能用于列名符合 Python 变量命名规则的情况，比如不能包含空格、不能以数字开头等
    - 例如 如果列名是 `First Name`，`Middle-Name` 或 `1stName`，就不能使用这种方式提取数据
    - 这就是为什么我们常说，在编程时，不论是给什么东西命名，最好都遵循变量命名规则，这样可以避免很多麻烦

In [100]:
df1.Name

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

### (2) 提取多列数据为 DataFrame

如果想要提取多列数据，提取出来以后还是 DataFrame，可以使用以下方式：

- 使用方括号 `df[['列名1', '列名2', ...]]`，这里需要使用双重方括号，外层方括号表示提取列，内层方括号表示列名的列表：

In [101]:
df1[["Name", "Age"]]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

- 这种方式提取一列数据时：`df[['列名']]`，提取出来的结果也是 DataFrame，而不是 Series，我们在前面的章节讨论过它们的区别

In [102]:
df1[["Name"]]

      Name
0    Alice
1      Bob
2  Charlie

## 2. 按行索引

如果想将行提取出来，主要有以下两种方式，我们之前其实介绍过：

- 使用 `iloc[行号]` 方法按顺序位置提取行数据，这种方式是不论行名是什么，谁在第几行就提取第几行
- 使用 `loc[行名]` 方法按行标签提取行数据

### (1) 使用 `iloc` 提取行数据

之前我们介绍过使用 `iloc` 方法提取一行数据，提取出来的一行其实是一个 Series：

In [103]:
df1.iloc[0]

Name        Alice
Age            25
City    Melbourne
Name: 0, dtype: object

事实上，`iloc` 方法还可以提取多行数据，提取出来的结果是一个 DataFrame：

- 一种语法结构是和 Python 中的列表切片类似的：`.iloc[起始行号:结束行号:步长]`

In [104]:
df1.iloc[0:2]

    Name  Age       City
0  Alice   25  Melbourne
1    Bob   30     Sydney

- 另一种语法结构是传入一个行号列表：`.iloc[[行号1, 行号2, ...]]`

In [105]:
df1.iloc[[0,2]]

      Name  Age       City
0    Alice   25  Melbourne
2  Charlie   35   Brisbane

### (2) 使用 `loc` 提取行数据

#### (a) 使用 `loc` 提取单行或多行数据

使用 `loc` 方法可以根据行标签（索引标签）提取行数据，提取出来的结果可以是 Series 或 DataFrame，具体取决于提取的是单行还是多行：

- 使用 `df.loc[行名]` 提取单行数据（这里传进去的是一个行标签），结果是一个 Series

In [106]:
df1.loc[0]

Name        Alice
Age            25
City    Melbourne
Name: 0, dtype: object

- 使用 `df.loc[[行名1, 行名2, ...]]` 提取多行数据（这里传进去的是一个列表），结果是一个 DataFrame

In [107]:
df1.loc[[0,1]]

    Name  Age       City
0  Alice   25  Melbourne
1    Bob   30     Sydney

- 使用 `df.loc[起始行名:结束行名]` 提取多行数据也是可以的，但是这种方法并不推荐：

    - 第一个原因是它**仅适用于行名是连续整数的情况**
    - 第二个原因是，这种方式和大家理解的切片有些出入，最终的结果是**包含结束行名对应的那一行数据的**

In [108]:
df1.loc[0:1]

    Name  Age       City
0  Alice   25  Melbourne
1    Bob   30     Sydney

由于我们使用的示例数据集的行名是默认的整数索引（0, 1, 2, ...），所以在这个例子中，`loc` 和 `iloc` 的效果类似，这里我们来看一个行名和顺序位置不一样的例子：

In [109]:
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Melbourne', 'Sydney', 'Brisbane']
}, index=[2, 1, 0])

df2

      Name  Age       City
2    Alice   25  Melbourne
1      Bob   30     Sydney
0  Charlie   35   Brisbane

In [110]:
df2.loc[0]

Name     Charlie
Age           35
City    Brisbane
Name: 0, dtype: object

In [111]:
df2.iloc[0]

Name        Alice
Age            25
City    Melbourne
Name: 2, dtype: object

在上面这个例子中：

- `df2.loc[0]` 提取的是行名为 0 的那一行数据，也就是 Charlie 的数据
- `df2.iloc[0]` 提取的是第 0 行数据，也就是 Alice 的数据
- 由于行名和行的顺序位置不一样，所以 `loc` 和 `iloc` 提取出来的数据也不一样

#### (b) Pandas 中常见的行名类型

在 Pandas 中，行名可以是多种类型，常见的有以下几种：

- 整数索引：这是最常见的行名类型，默认情况下，Pandas 会为 DataFrame 分配从 0 开始的整数索引，但是也有可能是混乱的整数顺序

In [112]:
df_rowname_1 = pd.DataFrame({
    'Name': ['David', 'Eva', 'Frank'],
    'Age': [28, 32, 29],
    'City': ['Adelaide', 'Perth', 'Hobart']
}, index=[0, 1, 2])

display(df_rowname_1)
display(df_rowname_1.loc[1])

    Name  Age      City
0  David   28  Adelaide
1    Eva   32     Perth
2  Frank   29    Hobart

Name      Eva
Age        32
City    Perth
Name: 1, dtype: object

- 字符串索引：行名可以是字符串类型，这种情况下，行名通常是有意义的标签，例如人名、城市名等

In [113]:
df_rowname_2 = pd.DataFrame({
    'Name': ['George', 'Hannah', 'Ian'],
    'Age': [40, 38, 45],
    'City': ['Canberra', 'Darwin', 'Cairns']
}, index=['person001', 'person002', 'person003'])

display(df_rowname_2)
display(df_rowname_2.loc['person002'])

             Name  Age      City
person001  George   40  Canberra
person002  Hannah   38    Darwin
person003     Ian   45    Cairns

Name    Hannah
Age         38
City    Darwin
Name: person002, dtype: object

- 日期时间索引：行名可以是日期时间类型，这在时间序列数据中非常常见

In [114]:
df_rowname_3 = pd.DataFrame({
    'Product': ['A', 'B', 'C'],
    'Value': [100, 200, 300],
}, index=pd.date_range(start='2023-01-01', periods=3, freq='D'))

display(df_rowname_3)
display(df_rowname_3.index)
display(df_rowname_3.loc['2023-01-02'])

           Product  Value
2023-01-01       A    100
2023-01-02       B    200
2023-01-03       C    300

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03'], dtype='datetime64[ns]', freq='D')

Product      B
Value      200
Name: 2023-01-02 00:00:00, dtype: object

- 区间索引：行名可以是区间类型，这在某些特定应用中可能会用到，例如表示年龄段、收入区间等，在取行名的时候，只要是在这个区间内的值，都可以取到对应的行数据

In [115]:
df_rowname_4 = pd.DataFrame({
    "tax_rate": [0.1, 0.15, 0.2, 0.25],
    "bracket_name": ["low", "medium", "high", "very_high"]
}, index=pd.IntervalIndex.from_tuples([(0, 20000), (20000, 50000), (50000, 100000), (100000, float('inf'))]))

display(df_rowname_4)
display(df_rowname_4.index)
display(df_rowname_4.loc[25000])
display(df_rowname_4.loc[35000])
display(df_rowname_4.loc[75000])

                     tax_rate bracket_name
(0.0, 20000.0]           0.10          low
(20000.0, 50000.0]       0.15       medium
(50000.0, 100000.0]      0.20         high
(100000.0, inf]          0.25    very_high

IntervalIndex([(0.0, 20000.0], (20000.0, 50000.0], (50000.0, 100000.0],
               (100000.0, inf]],
              dtype='interval[float64, right]')

tax_rate          0.15
bracket_name    medium
Name: (20000.0, 50000.0], dtype: object

tax_rate          0.15
bracket_name    medium
Name: (20000.0, 50000.0], dtype: object

tax_rate         0.2
bracket_name    high
Name: (50000.0, 100000.0], dtype: object

## 3. 按行与列同时索引

如果想同时提取某行和某列的数据：

- 一个比较直接的方法就是先提取列数据为一个新的 DataFrame，然后再从中提取行数据，或者反过来先行后列也行
- 这个大家组合我们上面介绍的内容就行，`loc` 与 `iloc` 混用也是可以的，这里我们就不赘述了

但是，其实 `loc` 和 `iloc` 方法都支持同时传入行和列的参数，可以一步到位地提取出某行某列的数据。

### (1) 使用 `iloc` 同时提取行和列数据

使用 `iloc` 方法时，可以同时传入行号和列号，语法结构如下：

- 第一个参数是行号，第二个参数是列号，都是基于位置的索引 `df.iloc[行号, 列号]`
- 例如，`df.iloc[1, 2]` 提取第 1 行第 2 列的数据

In [116]:
df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'George', 'Hannah', 'Ian'],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'M'],
    'Age': [25, 30, 35, 28, 32, 29, 40, 38, 45],
    'City': ['Melbourne', 'Sydney', 'Brisbane', 'Adelaide', 'Perth', 'Hobart', 'Canberra', 'Darwin', 'Cairns'],
    'Height_cm': [165, 175, 180, 170, 160, 178, 182, 168, 185],
    'Weight_kg': [60, 80, 75, 70, 55, 78, 85, 58, 90]
})

df3

      Name Gender  Age       City  Height_cm  Weight_kg
0    Alice      F   25  Melbourne        165         60
1      Bob      M   30     Sydney        175         80
2  Charlie      M   35   Brisbane        180         75
3    David      M   28   Adelaide        170         70
4      Eva      F   32      Perth        160         55
5    Frank      M   29     Hobart        178         78
6   George      M   40   Canberra        182         85
7   Hannah      F   38     Darwin        168         58
8      Ian      M   45     Cairns        185         90

In [117]:
df3.iloc[1, 2]

np.int64(30)

并且，`iloc` 也支持传入行号和列号的列表，以提取多行多列的数据：

- 一种是使用切片语法：`df.iloc[起始行号:结束行号:行号步长, 起始列号:结束列号:列号步长]`

In [118]:
df3.iloc[0:2, 1:3]

  Gender  Age
0      F   25
1      M   30

- 另一种是传入行号和列号的列表：`df.iloc[[行号1, 行号2, ...], [列号1, 列号2, ...]]`

In [119]:
df3.iloc[[0,2,3], [0,1,2]]

      Name Gender  Age
0    Alice      F   25
2  Charlie      M   35
3    David      M   28

- 当然，这两种结合使用也是可以的

In [120]:
df3.iloc[0:2, [0,1,2]]

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

除此之外，额外要说明的是：

- 如果想按列提取所有行的数据，可以在行号位置使用冒号 `:`，表示提取所有行
- 例如：`df.iloc[:, 列号]` 提取所有行的某些列数据

In [121]:
df3.iloc[:, [0,2]]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
4      Eva   32
5    Frank   29
6   George   40
7   Hannah   38
8      Ian   45

### (2) 使用 `loc` 同时提取行和列数据

使用 `loc` 方法时，可以同时传入行名和列名，语法结构就是 `df.loc[行名, 列名]`

In [122]:
df3.loc[0, 'Name']

'Alice'

如果想提取多行多列的数据，也可以传入行名和列名的列表：`df.loc[[行名1, 行名2, ...], [列名1, 列名2, ...]]`

In [123]:
df3.loc[[0,1], ['Name', 'Age', 'City']]

    Name  Age       City
0  Alice   25  Melbourne
1    Bob   30     Sydney

和 `iloc` 方法类似，`loc` 方法如果想提取某些列的所有行数据，也可以在行名位置使用冒号 `:`，表示提取所有行：

In [124]:
df3.loc[:, ['Name', 'Age', 'City']]

      Name  Age       City
0    Alice   25  Melbourne
1      Bob   30     Sydney
2  Charlie   35   Brisbane
3    David   28   Adelaide
4      Eva   32      Perth
5    Frank   29     Hobart
6   George   40   Canberra
7   Hannah   38     Darwin
8      Ian   45     Cairns

## 4. Pandas 数据索引的注意事项

大家在看别人代码时，可能会发现一种写法，就是直接 `df[数字或切片]` 的形式来提取数据，不用 `.loc` 或 `.iloc`

这种写法我们其实是不推荐的，因为它的使用有些复杂和抽象，容易引起误解：

- 首先，如果直接传入一个数字，例如 `df[3]`，Pandas 会尝试将其解释为**列名**，而不是行号：

    - 如果 DataFrame 中存在名为 3 的列，那么就会提取该列的数据
    - 如果不存在名为 3 的列，那么就会报错，提示找不到该列

- 其次，如果传入一个切片对象，例如 `df[1:4]`，Pandas 会将其解释为**行切片**：

    - 这时的效果是等同于 `df.iloc[1:4]`，也就是提取第 1 行到第 3 行的数据（不包含第 4 行）
    - 其他注意事项也和 `iloc` 方法类似

因此，大家会发现：

- 这种写法在提取数据时，行为和我们预期的不一样，传入数字提取列，传入切片提取行，很容易引起混淆
- 为了代码的可读性和一致性，建议大家始终使用 `loc` 或 `iloc` 方法来进行数据索引操作

## 5. Pandas 中的多级索引

### (1) 多级索引简介

在 Pandas 的表格中，有时候会遇到需要用多个层级来标识行或列的情况，这时就需要使用多级索引（MultiIndex）。

我们先来看下面这个表格：

<div align="center">
    <img src="./截屏2026-01-30 14.34.44.png" width="400"/>
</div>

- 这种表格在我们生活中十分常见，行名和列名都有多级结构，比如行名是年份和季度的组合，列名是品类和口味的组合
- 如果想定位到某个数值，就必须使用多级索引来指定行和列
- 比方说我们想要定位到2025年第二季度，薯片的烧烤味销量 61，这时就需要同时指定两个行级别和两个列级别的信息

在 Pandas 中定义这样一个多级索引的 DataFrame，可以使用 `pd.MultiIndex` 来创建行和列的多级索引：

- 具体来说，多级索引又分为常见的两种情况：

    - `pd.MultiIndex.from_product` 表示的是各级别之间是全组合关系，比如年份和季度的组合，2024年有四个季度，2025年也有四个季度，所以总共有 2 x 4 = 8 个行索引
    - `pd.MultiIndex.from_tuples` 则表示的是各级别之间是非全组合关系，比如品类和口味的组合，薯片有两种口味，饮料有两种口味，但是并不是每种品类都有所有的口味组合，这就需要我们手动指定每个组合的元组列表

- 这两种情况中，都还要指定每个级别的名称，方便后续定位数据时使用

In [125]:
df_multi = pd.DataFrame(
    [
        [10, 11, 12, 13],
        [20, 21, 22, 23],
        [30, 31, 32, 33],
        [40, 41, 42, 43],
        [50, 51, 52, 53],
        [60, 61, 62, 63],
        [70, 71, 72, 73],
        [80, 81, 82, 83],
    ],
    # 年和季度：全组合关系，使用 pd.MultiIndex.from_product
    index=pd.MultiIndex.from_product(
        [["2024年", "2025年"],
         ["第一季度", "第二季度", "第三季度", "第四季度"]],
        names=["年份", "季度"]
    ),
    # 品类和口味：非全组合关系，使用 pd.MultiIndex.from_tuples
    columns=pd.MultiIndex.from_tuples(
        [
            ("薯片", "番茄味"),
            ("薯片", "烧烤味"),
            ("冰淇淋", "香草味"),
            ("冰淇淋", "巧克力味"),
        ],
        names=["品类", "口味"]
    )
)

df_multi

品类          薯片     冰淇淋
口味         番茄味 烧烤味 香草味 巧克力味
年份    季度
2024年 第一季度  10  11  12   13
      第二季度  20  21  22   23
      第三季度  30  31  32   33
      第四季度  40  41  42   43
2025年 第一季度  50  51  52   53
      第二季度  60  61  62   63
      第三季度  70  71  72   73
      第四季度  80  81  82   83

在定义好多级索引的 DataFrame 以后，我们就可以使用 `loc` 方法来定位数据了：

- 这里的多级索引是通过元组来表示的，元组中的每个元素对应一个级别
- 例如：

    - `df_multi.loc[('2024年', '第一季度')]` 就表示定位到 2024 年第一季度的这一行数据
    - `df_multi.loc[:, ('薯片', '烧烤味')]` 就表示定位到薯片的烧烤味这一列数据
    - `df_multi.loc[('2025年', '第二季度'), ('薯片', '烧烤味')]` 就表示定位到 2025 年第二季度，薯片的烧烤味销量 61

In [126]:
df_multi.loc[('2024年', '第一季度')]

品类   口味
薯片   番茄味     10
     烧烤味     11
冰淇淋  香草味     12
     巧克力味    13
Name: (2024年, 第一季度), dtype: int64

In [127]:
df_multi.loc[:, ('薯片', '烧烤味')]

年份     季度
2024年  第一季度    11
       第二季度    21
       第三季度    31
       第四季度    41
2025年  第一季度    51
       第二季度    61
       第三季度    71
       第四季度    81
Name: (薯片, 烧烤味), dtype: int64

In [128]:
df_multi.loc[('2025年', '第二季度'), ('薯片', '烧烤味')]

np.int64(61)

### (2) 多级索引转换为单级索引

这种多级索引的表格，其实常常被用作数据透视表（Pivot Table），它可以帮助我们更好地展示数据。

- 但是，这种多级索引的数据透视表格式，在数据处理和分析时，可能会增加一些复杂度
- 因为多级索引的 DataFrame 在进行数据操作时，需要同时考虑多个级别的索引，这可能会导致代码变得复杂且难以维护
- 因此，在实际应用中，我们还是想用一种更简单的扁平化结构来存储和处理数据，也就是将多级索引转换为单级索引的形式

我们来看一个多级索引和单级索引转换的例子：

- 还是表达薯条和冰淇淋销量，多级索引的数据透视表是一种很直观的表示方式：

<div align="center">
    <img src="./截屏2026-01-30 14.34.44.png" width="500">
</div>

- 如果用单级索引，则是用一个长表格来表示相同的数据，这里其实就是讲索引全部变成新列中的值：

<div align="center">
    <img src="./截屏2026-01-31 23.16.29.png" width="500">
</div>

在 Pandas 中，将多级索引转换为单级索引，可以使用 `stack()` 方法：

- 具体来说，`stack()` 方法可以将 DataFrame 的某个级别的索引转换为行索引，从而实现多级索引到单级索引的转换
- 也就是说，想把列上的索引，想挪到行上，就填到 `stack()` 方法里面去
- 在我们这个例子中，数据的定位需要四个级别的信息，分别是年份、季度、品类、口味
- 而年份和季度本身就是行索引，所以我们只需要将品类和口味这两个列索引展开到行索引即可，也就是 `stack(["品类", "口味"])`
- 之后还要做两件事：

    - 一是多级索引的数据透视表中没有销量这一列名，需要用 `rename("销量")` 来命名
    - 二是将多级索引转换为普通列，可以使用 `reset_index()` 方法

In [129]:
df_multi_new1 = pd.DataFrame(
    [
        [10, 11, 12, 13],
        [20, 21, 22, 23],
        [30, 31, 32, 33],
        [40, 41, 42, 43],
        [50, 51, 52, 53],
        [60, 61, 62, 63],
        [70, 71, 72, 73],
        [80, 81, 82, 83],
    ],
    # 年和季度：全组合关系，使用 pd.MultiIndex.from_product
    index=pd.MultiIndex.from_product(
        [["2024年", "2025年"],
         ["第一季度", "第二季度", "第三季度", "第四季度"]],
        names=["年份", "季度"]
    ),
    # 品类和口味：非全组合关系，使用 pd.MultiIndex.from_tuples
    columns=pd.MultiIndex.from_tuples(
        [
            ("薯片", "番茄味"),
            ("薯片", "烧烤味"),
            ("冰淇淋", "香草味"),
            ("冰淇淋", "巧克力味"),
        ],
        names=["品类", "口味"]
    )
)

df_multi_new1

品类          薯片     冰淇淋
口味         番茄味 烧烤味 香草味 巧克力味
年份    季度
2024年 第一季度  10  11  12   13
      第二季度  20  21  22   23
      第三季度  30  31  32   33
      第四季度  40  41  42   43
2025年 第一季度  50  51  52   53
      第二季度  60  61  62   63
      第三季度  70  71  72   73
      第四季度  80  81  82   83

In [130]:
df_single_new1 = (
    df_multi_new1
    .stack(["品类", "口味"], future_stack=True)      # 把列索引展开到行索引，并且保留未来版本兼容性，因为 stack 方法未来版本会改变默认行为
    .rename("销量")              # Series 命名
    .reset_index()              # 变成普通列：年份、季度、品类、口味、销量
)

df_single_new1

       年份    季度   品类    口味  销量
0   2024年  第一季度   薯片   番茄味  10
1   2024年  第一季度   薯片   烧烤味  11
2   2024年  第一季度  冰淇淋   香草味  12
3   2024年  第一季度  冰淇淋  巧克力味  13
4   2024年  第二季度   薯片   番茄味  20
5   2024年  第二季度   薯片   烧烤味  21
6   2024年  第二季度  冰淇淋   香草味  22
7   2024年  第二季度  冰淇淋  巧克力味  23
8   2024年  第三季度   薯片   番茄味  30
9   2024年  第三季度   薯片   烧烤味  31
10  2024年  第三季度  冰淇淋   香草味  32
11  2024年  第三季度  冰淇淋  巧克力味  33
12  2024年  第四季度   薯片   番茄味  40
13  2024年  第四季度   薯片   烧烤味  41
14  2024年  第四季度  冰淇淋   香草味  42
15  2024年  第四季度  冰淇淋  巧克力味  43
16  2025年  第一季度   薯片   番茄味  50
17  2025年  第一季度   薯片   烧烤味  51
18  2025年  第一季度  冰淇淋   香草味  52
19  2025年  第一季度  冰淇淋  巧克力味  53
20  2025年  第二季度   薯片   番茄味  60
21  2025年  第二季度   薯片   烧烤味  61
22  2025年  第二季度  冰淇淋   香草味  62
23  2025年  第二季度  冰淇淋  巧克力味  63
24  2025年  第三季度   薯片   番茄味  70
25  2025年  第三季度   薯片   烧烤味  71
26  2025年  第三季度  冰淇淋   香草味  72
27  2025年  第三季度  冰淇淋  巧克力味  73
28  2025年  第四季度   薯片   番茄味  80
29  2025年  第四季度   薯片   烧烤味  81
30  2025年  第四季度  冰淇淋   香草味  82
31  2025年  第四季度  冰淇淋  巧克力味  83

这里我们来看一下，如果不加 `reset_index()` 会怎么样：

- 这里我们需加上 `.to_frame()` 否则结果不是 DataFrame，只是个 Series：

In [131]:
df_multi_new1.stack(["品类", "口味"], future_stack=True).rename("销量").to_frame()

                     销量
年份    季度   品类  口味
2024年 第一季度 薯片  番茄味   10
               烧烤味   11
           冰淇淋 香草味   12
               巧克力味  13
      第二季度 薯片  番茄味   20
               烧烤味   21
           冰淇淋 香草味   22
               巧克力味  23
      第三季度 薯片  番茄味   30
               烧烤味   31
           冰淇淋 香草味   32
               巧克力味  33
      第四季度 薯片  番茄味   40
               烧烤味   41
           冰淇淋 香草味   42
               巧克力味  43
2025年 第一季度 薯片  番茄味   50
               烧烤味   51
           冰淇淋 香草味   52
               巧克力味  53
      第二季度 薯片  番茄味   60
               烧烤味   61
           冰淇淋 香草味   62
               巧克力味  63
      第三季度 薯片  番茄味   70
               烧烤味   71
           冰淇淋 香草味   72
               巧克力味  73
      第四季度 薯片  番茄味   80
               烧烤味   81
           冰淇淋 香草味   82
               巧克力味  83

- 可以看到，虽然四个级别的索引都展开到了行索引中，但是它们依然是多级索引的形式，类似于 Excel 中合并了单元格的产物，不是普通列
- 只有加了 `reset_index()`，才能将多级索引转换为普通列，变成我们想要的单级索引格式：

In [132]:
df_multi_new1.stack(["品类", "口味"], future_stack=True).rename("销量").reset_index()

       年份    季度   品类    口味  销量
0   2024年  第一季度   薯片   番茄味  10
1   2024年  第一季度   薯片   烧烤味  11
2   2024年  第一季度  冰淇淋   香草味  12
3   2024年  第一季度  冰淇淋  巧克力味  13
4   2024年  第二季度   薯片   番茄味  20
5   2024年  第二季度   薯片   烧烤味  21
6   2024年  第二季度  冰淇淋   香草味  22
7   2024年  第二季度  冰淇淋  巧克力味  23
8   2024年  第三季度   薯片   番茄味  30
9   2024年  第三季度   薯片   烧烤味  31
10  2024年  第三季度  冰淇淋   香草味  32
11  2024年  第三季度  冰淇淋  巧克力味  33
12  2024年  第四季度   薯片   番茄味  40
13  2024年  第四季度   薯片   烧烤味  41
14  2024年  第四季度  冰淇淋   香草味  42
15  2024年  第四季度  冰淇淋  巧克力味  43
16  2025年  第一季度   薯片   番茄味  50
17  2025年  第一季度   薯片   烧烤味  51
18  2025年  第一季度  冰淇淋   香草味  52
19  2025年  第一季度  冰淇淋  巧克力味  53
20  2025年  第二季度   薯片   番茄味  60
21  2025年  第二季度   薯片   烧烤味  61
22  2025年  第二季度  冰淇淋   香草味  62
23  2025年  第二季度  冰淇淋  巧克力味  63
24  2025年  第三季度   薯片   番茄味  70
25  2025年  第三季度   薯片   烧烤味  71
26  2025年  第三季度  冰淇淋   香草味  72
27  2025年  第三季度  冰淇淋  巧克力味  73
28  2025年  第四季度   薯片   番茄味  80
29  2025年  第四季度   薯片   烧烤味  81
30  2025年  第四季度  冰淇淋   香草味  82
31  2025年  第四季度  冰淇淋  巧克力味  83

### (3) 单级索引转换为多级索引

当然，单级索引转换为多级索引也是可以的，可以使用 `unstack()` 方法：

- 和 `stack()` 方法相反，`unstack()` 方法是将行索引的某个级别转换为列索引，从而实现单级索引到多级索引的转换
- 也就是说，在行上的索引，想挪到列上，就填到 `unstack()` 方法里面去
- 在我们这个例子中，假如说我们手头有的是上面这个单级索引的 DataFrame，我们想把品类和口味挪到列上，就要用 `unstack(["品类", "口味"])`
- 除此之外，还有两件事需要注意：

    - 一是在使用 `unstack()` 方法之前，要先将**所有级别的索引设置为行索引**，可以使用 `set_index()` 方法
    - 二是要选择数值列，也就是将哪一列进行数据透视，比如 `["销量"]`

In [133]:
df_single_new2 = pd.DataFrame({
    "年份": [
        "2024年","2024年","2024年","2024年",
        "2024年","2024年","2024年","2024年",
        "2024年","2024年","2024年","2024年",
        "2024年","2024年","2024年","2024年",
        "2025年","2025年","2025年","2025年",
        "2025年","2025年","2025年","2025年",
        "2025年","2025年","2025年","2025年",
        "2025年","2025年","2025年","2025年",
    ],
    "季度": [
        "第一季度","第一季度","第一季度","第一季度",
        "第二季度","第二季度","第二季度","第二季度",
        "第三季度","第三季度","第三季度","第三季度",
        "第四季度","第四季度","第四季度","第四季度",
        "第一季度","第一季度","第一季度","第一季度",
        "第二季度","第二季度","第二季度","第二季度",
        "第三季度","第三季度","第三季度","第三季度",
        "第四季度","第四季度","第四季度","第四季度",
    ],
    "品类": [
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
        "薯片","薯片","冰淇淋","冰淇淋",
    ],
    "口味": [
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
        "番茄味","烧烤味","香草味","巧克力味",
    ],
    "销量": [
        10,11,12,13,
        20,21,22,23,
        30,31,32,33,
        40,41,42,43,
        50,51,52,53,
        60,61,62,63,
        70,71,72,73,
        80,81,82,83,
    ]
})

df_single_new2

       年份    季度   品类    口味  销量
0   2024年  第一季度   薯片   番茄味  10
1   2024年  第一季度   薯片   烧烤味  11
2   2024年  第一季度  冰淇淋   香草味  12
3   2024年  第一季度  冰淇淋  巧克力味  13
4   2024年  第二季度   薯片   番茄味  20
5   2024年  第二季度   薯片   烧烤味  21
6   2024年  第二季度  冰淇淋   香草味  22
7   2024年  第二季度  冰淇淋  巧克力味  23
8   2024年  第三季度   薯片   番茄味  30
9   2024年  第三季度   薯片   烧烤味  31
10  2024年  第三季度  冰淇淋   香草味  32
11  2024年  第三季度  冰淇淋  巧克力味  33
12  2024年  第四季度   薯片   番茄味  40
13  2024年  第四季度   薯片   烧烤味  41
14  2024年  第四季度  冰淇淋   香草味  42
15  2024年  第四季度  冰淇淋  巧克力味  43
16  2025年  第一季度   薯片   番茄味  50
17  2025年  第一季度   薯片   烧烤味  51
18  2025年  第一季度  冰淇淋   香草味  52
19  2025年  第一季度  冰淇淋  巧克力味  53
20  2025年  第二季度   薯片   番茄味  60
21  2025年  第二季度   薯片   烧烤味  61
22  2025年  第二季度  冰淇淋   香草味  62
23  2025年  第二季度  冰淇淋  巧克力味  63
24  2025年  第三季度   薯片   番茄味  70
25  2025年  第三季度   薯片   烧烤味  71
26  2025年  第三季度  冰淇淋   香草味  72
27  2025年  第三季度  冰淇淋  巧克力味  73
28  2025年  第四季度   薯片   番茄味  80
29  2025年  第四季度   薯片   烧烤味  81
30  2025年  第四季度  冰淇淋   香草味  82
31  2025年  第四季度  冰淇淋  巧克力味  83

In [134]:
df_multi_new2 = (
    df_single_new2
    .set_index(["年份", "季度", "品类", "口味"])["销量"]
    .unstack(["品类", "口味"])
)

df_multi_new2

品类          薯片     冰淇淋
口味         番茄味 烧烤味 香草味 巧克力味
年份    季度
2024年 第一季度  10  11  12   13
      第三季度  30  31  32   33
      第二季度  20  21  22   23
      第四季度  40  41  42   43
2025年 第一季度  50  51  52   53
      第三季度  70  71  72   73
      第二季度  60  61  62   63
      第四季度  80  81  82   83