# Topic 2.8 - Pandas 中的数据连接与拼接

在本节开始之前，我们先导入 pandas 库：

In [1]:
import pandas as pd

## 1. 数据连接

### (1) 数据连接的概念

数据连接的概念，是将两个表按照某些公共的列，将它们连接在一起，类似于数据库中的 `JOIN` 操作：

- 这个操作听上去有点高大上，但是底层逻辑十分简单，我们先来看个以下例子：

<div align="center">
    <img src="./截屏2026-02-01 23.25.32.png" width="800">
</div>


- 上图中，我们有两个表，一个表中包含的列是姓名和班级，另一个表中包含的列是班级和班主任
- 我们可以通过 `班级` 这个公共列，将两个表连接在一起，得到一个新的表，这个新表中包含了姓名、班级和班主任三列

数据连接的操作，可以使用 Pandas 中的 `merge()` 函数来实现：

In [2]:
df1a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班"]
})

df1a

   姓名  班级
0  张三  一班
1  李四  一班
2  王五  一班
3  赵六  二班
4  牛七  二班
5  马八  三班
6  杨九  三班

In [3]:
df1b = pd.DataFrame({
    "班级": ["一班", "二班", "三班"],
    "班主任": ["老A", "老B", "老C"]
})

df1b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C

In [4]:
df_merged1 = pd.merge(df1a, df1b, on="班级")
df_merged1

   姓名  班级 班主任
0  张三  一班  老A
1  李四  一班  老A
2  王五  一班  老A
3  赵六  二班  老B
4  牛七  二班  老B
5  马八  三班  老C
6  杨九  三班  老C

### (2) 常见的连接方式

连接方式这个概念，是建立在两表连接键（公共列）上，决定如何连接两表的规则，我们这里来介绍一些常见的连接方式。


#### (a) 内连接

内连接（Inner Join）：只保留两个表中连接键匹配的行：

- 使用集合来表示，内连接就是两个表连接键的交集：

<div align="center">
    <img src="./UI25E_副本.jpg" width="200">
</div>


- 回到班级的这个例子中，一个内连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 14.35.11.png" width="800">
</div>

- 通过内连接，我们只保留了两个表中 `班级` 列匹配的行：

    - 左表中 `Alice`、`Bob` 和 `Charlie` 三行的 `班级` 分别是 `四班`、`四班` 和 `六班`，在右表中没有对应的 `班级`，所以这三行被丢弃了
    - 右表中，`五班` 的班主任 `老E`，在左表中没有对应的 `班级`，所以这一行也被丢弃了

- 事实上，在 Pandas 中，`merge()` 函数的默认连接方式就是内连接，如果想强调是内连接，可以通过 `how='inner'` 参数来指定：

In [5]:
df2a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df2a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [6]:
df2b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df2b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [7]:
df_merged2 = pd.merge(df2a, df2b, on="班级", how="inner")
df_merged2

   姓名  班级 班主任
0  张三  一班  老A
1  李四  一班  老A
2  王五  一班  老A
3  赵六  二班  老B
4  牛七  二班  老B
5  马八  三班  老C
6  杨九  三班  老C

#### (b) 左连接

左连接（Left Join）：左表是老大，保留左表的所有行，在左表但不在右表中的键用 NaN 填充

- 使用集合来表示，左连接就是左表连接键的全集：

<div align="center">
    <img src="./UI25E_副本2.jpg" width="200">
</div>

- 回到班级的这个例子中，一个左连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 14.49.59.png" width="800">
</div>

- 通过左连接，我们保留了左表中的所有行：

    - 左表中 `Alice`、`Bob` 和 `Charlie` 三行的 `班级` 分别是 `四班`、`四班` 和 `六班`，在右表中没有对应的 `班级`，所以这三行的 `班主任` 列被填充为 NaN
    - 右表中，`五班` 的班主任 `老E`，在左表中没有对应的 `班级`，所以这一行被丢弃了

- 在 Pandas 中，可以通过在 `merge()` 函数中指定 `how='left'` 参数来指定左连接：

In [8]:
df3a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df3a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [9]:
df3b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df3b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [10]:
df_merged3 = pd.merge(df3a, df3b, on="班级", how="left")
df_merged3

        姓名  班级  班主任
0       张三  一班   老A
1       李四  一班   老A
2       王五  一班   老A
3       赵六  二班   老B
4       牛七  二班   老B
5       马八  三班   老C
6       杨九  三班   老C
7    Alice  四班  NaN
8      Bob  四班  NaN
9  Charlie  六班  NaN

#### (c) 右连接

右连接（Right Join）：右表是老大，保留右表的所有行，在右表但不在左表中的键用 NaN 填充

- 使用集合来表示，右连接就是右表连接键的全集：

<div align="center">
    <img src="./UI25E_副本3.jpg" width="200">
</div>

- 回到班级的这个例子中，一个右连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 15.16.01.png" width="800">
</div>

- 通过右连接，我们保留了右表中的所有行：

    - 左表中 `Alice`、`Bob` 和 `Charlie` 三行的 `班级` 分别是 `四班`、`四班` 和 `六班`，在右表中没有对应的 `班级`，所以这三行被丢弃了
    - 右表中，`五班` 的班主任 `老E`，在左表中没有对应的 `班级`，所以这一行的 `姓名` 列被填充为 NaN

- 在 Pandas 中，可以通过在 `merge()` 函数中指定 `how='right'` 参数来指定右连接：

In [11]:
df4a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df4a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [12]:
df4b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df4b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [13]:
df_merged4 = pd.merge(df4a, df4b, on="班级", how="right")
df_merged4

    姓名  班级 班主任
0   张三  一班  老A
1   李四  一班  老A
2   王五  一班  老A
3   赵六  二班  老B
4   牛七  二班  老B
5   马八  三班  老C
6   杨九  三班  老C
7  NaN  五班  老E

#### (d) 外连接

外连接（Outer Join）：左连接和右连接的结合，保留两个表中的所有行，不匹配的键用 NaN 填充

- 使用集合来表示，外连接就是两个表连接键的并集：

<div align="center">
    <img src="./UI25E_副本4.jpg" width="200">
</div>

- 回到班级的这个例子中，一个外连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 15.28.19.png" width="800">
</div>

- 通过外连接，我们保留了两个表中的所有行：

    - 左表中 `Alice`、`Bob` 和 `Charlie` 三行的 `班级` 分别是 `四班`、`四班` 和 `六班`，在右表中没有对应的 `班级`，所以这三行的 `班主任` 列被填充为 NaN
    - 右表中，`五班` 的班主任 `老E`，在左表中没有对应的 `班级`，所以这一行的 `姓名` 列被填充为 NaN

- 在 Pandas 中，可以通过在 `merge()` 函数中指定 `how='outer'` 参数来指定外连接：

In [14]:
df5a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df5a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [15]:
df5b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df5b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [16]:
df_merged5 = pd.merge(df5a, df5b, on="班级", how="outer")
df_merged5

         姓名  班级  班主任
0        张三  一班   老A
1        李四  一班   老A
2        王五  一班   老A
3        马八  三班   老C
4        杨九  三班   老C
5        赵六  二班   老B
6        牛七  二班   老B
7       NaN  五班   老E
8   Charlie  六班  NaN
9     Alice  四班  NaN
10      Bob  四班  NaN

### (3) 特殊的连接方式

上面四种连接方式是比较常见的连接方式，除此之外，还有一些特殊的连接方式，使用场景相对较少，这里我们简单介绍。

#### (a) 左反连接

左反连接（Left Anti Join）：只保留左表中不在右表中的行

- 从集合的角度来看，左反连接就是左连接的基础上，去掉了交集部分：

<div align="center">
    <img src="./UI25E_副本5.jpg" width="200">
</div>

- 回到班级的这个例子中，一个左反连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 15.47.25.png" width="800">
</div>

- 通过左反连接，我们只保留了左表中的特有行

- 在 Pandas 中，可以通过在 `merge()` 函数中指定 `how='left'` 参数，并结合 `indicator=True` 参数来实现左反连接：

    - `indicator=True` 参数会在结果中添加一列 `_merge`，标识每一行的来源，原来是在左表中（`left_only`）还是右表中（`right_only`），还是两个表中都有（`both`）
    - 然后我们可以通过筛选仅仅在左表中的行 `left_only`，来实现左反连接
    - 之后再把 `_merge` 列删除即可

In [17]:
df6a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df6a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [18]:
df6b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df6b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [19]:
df_merged6 = pd.merge(df6a, df6b, on="班级", how="outer", indicator=True).query("_merge == 'left_only'").drop(columns="_merge")
df_merged6

         姓名  班级  班主任
8   Charlie  六班  NaN
9     Alice  四班  NaN
10      Bob  四班  NaN

#### (b) 右反连接

右反连接（Right Anti Join）：只保留右表中不在左表中的行

- 从集合的角度来看，右反连接就是右连接的基础上，去掉了交集部分：

<div align="center">
    <img src="./UI25E_副本6.jpg" width="200">
</div>

- 回到班级的这个例子中，一个右反连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 15.57.45.png" width="800">
</div>

- 通过右反连接，我们只保留了右表中的特有行

- 在 Pandas 中，可以通过在 `merge()` 函数中指定 `how='right'` 参数，并结合 `indicator=True` 参数来实现右反连接：

    - `indicator=True` 参数会在结果中添加一列 `_merge`，标识每一行的来源，原来是在左表中（`left_only`）还是右表中（`right_only`），还是两个表中都有（`both`）
    - 然后我们可以通过筛选仅仅在右表中的行 `right_only`，来实现右反连接
    - 之后再把 `_merge` 列删除即可

In [20]:
df7a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df7a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [21]:
df7b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df7b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [22]:
df_merged7 = pd.merge(df7a, df7b, on="班级", how="outer", indicator=True).query("_merge == 'right_only'").drop(columns="_merge")
df_merged7

    姓名  班级 班主任
7  NaN  五班  老E

#### (c) 全反连接

全反连接（Full Anti Join）：只保留两个表中不匹配的行，可以看作左反连接和右反连接的结合

- 从集合的角度来看，全反连接就是外连接的基础上，去掉了交集部分：

<div align="center">
    <img src="./UI25E_副本7.jpg" width="200">
</div>

- 回到班级的这个例子中，一个全反连接的例子可以用下图来表示：

<div align="center">
    <img src="./截屏2026-02-02 16.06.01.png" width="800">
</div>

- 通过全反连接，我们只保留了两个表中的特有行

- 在 Pandas 中，可以通过在 `merge()` 函数中指定 `how='outer'` 参数，并结合 `indicator=True` 参数来实现全反连接：

    - `indicator=True` 参数会在结果中添加一列 `_merge`，标识每一行的来源，原来是在左表中（`left_only`）还是右表中（`right_only`），还是两个表中都有（`both`）
    - 然后我们可以通过筛选不是 `both` 的行，来实现全反连接
    - 之后再把 `_merge` 列删除即可

In [23]:
df8a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八", "杨九", "Alice", "Bob", "Charlie"],
    "班级": ["一班", "一班", "一班", "二班", "二班", "三班", "三班", "四班", "四班", "六班"]
})

df8a

        姓名  班级
0       张三  一班
1       李四  一班
2       王五  一班
3       赵六  二班
4       牛七  二班
5       马八  三班
6       杨九  三班
7    Alice  四班
8      Bob  四班
9  Charlie  六班

In [24]:
df8b = pd.DataFrame({
    "班级": ["一班", "二班", "三班", "五班"],
    "班主任": ["老A", "老B", "老C", "老E"]
})

df8b

   班级 班主任
0  一班  老A
1  二班  老B
2  三班  老C
3  五班  老E

In [25]:
df_merged8 = pd.merge(df8a, df8b, on="班级", how="outer", indicator=True).query("_merge != 'both'").drop(columns="_merge")
df_merged8

         姓名  班级  班主任
7       NaN  五班   老E
8   Charlie  六班  NaN
9     Alice  四班  NaN
10      Bob  四班  NaN

### (4) 多键连接

多键连接是指在连接两个表时，使用多个列作为连接键，而不是单一的列：

- 多键连接的应用情景是，有的时候数据的标识信息可能不止一个列能够唯一标识，这时候就需要使用多个列来进行连接
- 比方说，假设我们将学生表修改修改，班级的标识要使用 `年级` 和 `班级` 两列来共同标识：

<div align="center">
    <img src="./截屏2026-02-02 16.20.07.png" width="800">
</div>

在 Pandas 中，可以通过在 `merge()` 函数中传入一个包含多个列名的列表，来实现多键连接：

In [26]:
df9a = pd.DataFrame({
    "姓名": ["张三", "李四", "王五", "赵六", "牛七", "马八"],
    "年级": ["一年级", "一年级", "二年级", "二年级", "二年级", "二年级"],
    "班级": ["一班", "二班", "一班", "二班", "二班", "三班"]
})

df9a

   姓名   年级  班级
0  张三  一年级  一班
1  李四  一年级  二班
2  王五  二年级  一班
3  赵六  二年级  二班
4  牛七  二年级  二班
5  马八  二年级  三班

In [27]:
df9b = pd.DataFrame({
    "年级": ["一年级", "一年级", "二年级", "二年级", "二年级"],
    "班级": ["一班", "二班", "一班", "二班", "三班"],
    "班主任": ["老A", "老B", "老C", "老D", "老E"]
})

df9b

    年级  班级 班主任
0  一年级  一班  老A
1  一年级  二班  老B
2  二年级  一班  老C
3  二年级  二班  老D
4  二年级  三班  老E

In [28]:
df_merged9 = pd.merge(df9a, df9b, on=["年级", "班级"], how="inner")
df_merged9

   姓名   年级  班级 班主任
0  张三  一年级  一班  老A
1  李四  一年级  二班  老B
2  王五  二年级  一班  老C
3  赵六  二年级  二班  老D
4  牛七  二年级  二班  老D
5  马八  二年级  三班  老E

在多键连接的情境下，我们上面介绍的各种连接方式依然适用，只不过连接键变成了多个列，这里我们就不再赘述了。

## 2. 数据拼接

数据拼接，其实要比数据连接简单很多，数据拼接就是将两个表在行或者列的方向上进行拼接，并不用考虑连接键的问题。

### (1) 按行拼接

将两个表或多个表按行拼接，也就是纵向拼接，也就是添加新行，可以使用 Pandas 中的 `concat()` 函数来实现：

- 在这个函数中，我们只需要传入一个包含多个 DataFrame 的列表，然后指定 `axis=0` 参数即可实现按行拼接
- 按行拼接的条件是，所有被拼接的表必须具有相同的列结构，也就是说**列名、列数、列顺序**必须一致
- 在使用完 `concat()` 函数拼接之后，行的索引会继承原表的索引，如果想要重新生成连续的索引，可以再接一个 `.reset_index(drop=True)` 方法

In [29]:
df_new1 = pd.DataFrame({
    "姓名": ["张三", "李四", "王五"],
    "班级": ["一班", "一班", "一班"]
})

df_new1

   姓名  班级
0  张三  一班
1  李四  一班
2  王五  一班

In [30]:
df_new2 = pd.DataFrame({
    "姓名": ["赵六", "牛七"],
    "班级": ["二班", "二班"]
})

df_new2

   姓名  班级
0  赵六  二班
1  牛七  二班

In [31]:
df_concatenated1 = pd.concat([df_new1, df_new2], axis=0).reset_index(drop=True)
df_concatenated1

   姓名  班级
0  张三  一班
1  李四  一班
2  王五  一班
3  赵六  二班
4  牛七  二班

### (2) 按列拼接

将两个表或多个表按列拼接，也就是横向拼接，也就是添加新列，可以使用 Pandas 中的 `concat()` 函数来实现：

- 在这个函数中，我们只需要传入一个包含多个 DataFrame 的列表，然后指定 `axis=1` 参数即可实现按列拼接
- 按列拼接的条件是，所有被拼接的表必须具有相同的行数，也就是说**行数**必须一致，这里对列是没有什么要求的，因为横向拼接的操作其实就是添加新列
- 在使用完 `concat()` 函数拼接之后，列的索引会继承原表的列索引，如果想要重新生成连续的列索引，可以再接一个 `.reset_index(drop=True, axis=1)` 方法

In [32]:
df_new3 = pd.DataFrame({
    "姓名": ["张三", "李四", "王五"],
    "班级": ["一班", "一班", "一班"]
})

df_new3

   姓名  班级
0  张三  一班
1  李四  一班
2  王五  一班

In [33]:
df_new4 = pd.DataFrame({
    "数学": [80, 90, 85],
    "语文": [75, 88, 92],
    "英语": [78, 85, 80]
})

df_new4

   数学  语文  英语
0  80  75  78
1  90  88  85
2  85  92  80

In [34]:
df_concatenated2 = pd.concat([df_new3, df_new4], axis=1).reset_index(drop=True)
df_concatenated2

   姓名  班级  数学  语文  英语
0  张三  一班  80  75  78
1  李四  一班  90  88  85
2  王五  一班  85  92  80